# Change these first
owner: sensioty # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Sensioty Website
    icon: https://www.sensioty.ch/wp-content/uploads/2020/09/Favicon_32.png
    url: https://www.sensioty.ch
    assignees:
      - sdnussb
  - name: Klaudia.io Application
    icon: https://app.klaudia.io/de/assets/favicon-32x32.png
    url: https://app.klaudia.io
  - name: Klaudia.io API
    icon: https://app.klaudia.io/de/assets/favicon-32x32.png
    url: $URL_API_SERVER
  # TCP ping seems not to work
  # See also: https://github.com/upptime/upptime/issues/436
  #- name: Gateway MQTT
  #  icon: https://app.klaudia.io/de/assets/favicon-32x32.png
  #  check: "tcp-ping"
  #  url: $URL_GATEWAY_MQTT
  #  port: 1883

assignees: # Users to assign downtime issues (optional)
  - UncleSamSwiss

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sensioty.ch
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/sensioty/upptime/master/assets/logo.png
  name: Sensioty AG
  introTitle: "**Sensioty AG** Online Services Status"
  introMessage: Powered by [Upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
